// Generated by cargo run -p worklens-core --bin export-contracts. Do not edit.
export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;
export type Provenance = { source: string, collectedAt: string, status: Availability, detail: string | null, revision: string | null, };
export type Availability = "available" | "partial" | "stale" | "unavailable";
export type Repository = { id: string, name: string, path: string, commonDir: string, trusted: boolean, };
export type FileChange = { path: string, previousPath: string | null, indexStatus: string, worktreeStatus: string, };
export type Worktree = { id: string, path: string, head: string, branch: string | null, locked: boolean, prunable: boolean, };
export type Branch = { name: string, head: string, upstream: string | null, tracking: string, };
export type Remote = { name: string, url: string, };
export type Commit = { sha: string, parents: Array<string>, author: string, date: string, subject: string, };
export type GitSnapshot = { repository: Repository, branch: string | null, head: string | null, changes: Array<FileChange>, branches: Array<Branch>, remotes: Array<Remote>, worktrees: Array<Worktree>, commits: Array<Commit>, nextOffset: number | null, provenance: Provenance, };
export type DiffResult = { text: string, truncated: boolean, binary: boolean, provenance: Provenance, };
export type Document = { path: string, title: string, };
export type ToolStatus = { tool: string, available: boolean, version: string, };
export type RelationKind = "project_dependency" | "package_dependency" | "task_dependency" | "contains";
export type Evidence = "observed" | "declared" | "candidate";
export type Project = { id: string, name: string, root: string, kind: string, ecosystem: string, manifest: string, external: boolean, targets: Array<string>, features: Array<string>, };
export type Edge = { source: string, target: string, kind: RelationKind, evidence: Evidence, origin: string, };
export type Graph = { nodes: Array<Project>, edges: Array<Edge>, sources: Array<Provenance>, };
export type Impact = { direct: Array<string>, dependants: Array<string>, warning: string, };
export type PrRevision = { baseRepository: string, headRepository: string | null, baseSha: string, headSha: string, expectedFiles: number, };
export type PrChangedFile = { path: string, previousPath: string | null, status: string, };
export type PrFileCollection = { revision: PrRevision, files: Array<PrChangedFile>, pagesCollected: number, revisionVerified: boolean, provenance: Provenance, warnings: Array<string>, };
export type ImpactMatch = { project: Project, paths: Array<string>, };
export type ImpactDependent = { project: Project, via: Edge, };
export type DetailedImpact = { direct: Array<ImpactMatch>, dependants: Array<ImpactDependent>, unmatched: Array<string>, transversal: Array<string>, };
export type PrImpact = { collection: PrFileCollection, graphSources: Array<Provenance>, graphWorktree: string, graphHead: string | null, graphMatchesHead: boolean, impact: DetailedImpact, warnings: Array<string>, };
export type ValidationKind = "check" | "status";
export type ValidationOutcome = "success" | "failure" | "pending" | "cancelled" | "skipped" | "neutral" | "timed_out" | "action_required" | "unknown" | "missing" | "ambiguous";
export type ValidationExpectation = { repository: string, kind: ValidationKind, name: string, appId: number | null, };
export type ValidationObservation = { id: string, kind: ValidationKind, name: string, appId: number | null, sha: string, outcome: ValidationOutcome, rawState: string, url: string | null, };
export type ValidationAssessment = { expectation: ValidationExpectation, outcome: ValidationOutcome, matches: Array<string>, };
export type ValidationReport = { repository: string, sha: string, workRevision: number | null, observations: Array<ValidationObservation>, assessments: Array<ValidationAssessment>, sources: Array<Provenance>, summary: string, warnings: Array<string>, };
export type AgentState = "active" | "waiting" | "blocked" | "completed" | "failed";
export type AgentSession = { id: string, repositoryId: string, worktree: string, tool: string, objective: string, state: AgentState, message: string, lastSeen: string, presence: string, issue: string | null, pr: string | null, };
export type Operation = "open" | "recent" | "trust" | "status" | "git" | "diff" | "projects" | "graph" | "tasks" | "impact" | "pr_impact" | "validations" | "documents" | "document" | "context" | "doctor" | "agents" | "agent_start" | "agent_update" | "agent_heartbeat" | "agent_finish" | "github_auth_start" | "github_auth_poll" | "github_auth_status" | "github_logout" | "issues" | "prs" | "pr" | "issue" | "ci" | "run" | "logs" | "search" | "work_list" | "work_show" | "work_create" | "work_update" | "work_link" | "work_unlink" | "work_note" | "work_expectations" | "work_decision_request" | "work_decision_answer" | "work_decision_cancel";
export type WorkState = "todo" | "in_progress" | "waiting" | "blocked" | "completed" | "abandoned";
export type WorkLinkKind = "pr" | "issue" | "worktree" | "agent" | "component";
export type WorkLinkStatus = "candidate" | "confirmed" | "rejected";
export type WorkLink = { kind: WorkLinkKind, reference: string, status: WorkLinkStatus, reason: string, };
export type WorkItem = { id: string, repositoryId: string, title: string, objective: string, criteria: string, state: WorkState, revision: number, links: Array<WorkLink>, expectations: Array<ValidationExpectation>, decisions: Array<Decision>, createdAt: string, updatedAt: string, };
export type DecisionRequest = { id: string, question: string,
/**
 * Explicit scope/evidence supplied by the requester, not executable instructions.
 */
context: string, options: Array<string>, };
export type DecisionResolution = { "state": "pending" } | { "state": "answered", answer: string, reason: string, actor: string, at: string, } | { "state": "cancelled", reason: string, actor: string, at: string, };
export type Decision = { request: DecisionRequest,
/**
 * Revision inspected when requesting the decision. Not an authorization for later revisions.
 */
workRevision: number,
/**
 * Caller-declared attribution; never an authenticated human identity.
 */
requestedBy: string, requestedAt: string, resolution: DecisionResolution, };
export type WorkEvent = { eventId: string, revision: number, action: string,
/**
 * Attribution is explicitly supplied by the caller, not an authenticated identity.
 */
actor: string, createdAt: string, details: JsonValue, };
export type WorkDetail = { item: WorkItem, events: Array<WorkEvent>, nextOffset: number | null, };
export type WorkList = { items: Array<WorkItem>, nextOffset: number | null, };
export type WorkResult = { applied: boolean, item: WorkItem, };
export type WorkChange = { "action": "decision_request", decision: DecisionRequest, } | { "action": "decision_answer", id: string, answer: string, reason: string, } | { "action": "decision_cancel", id: string, reason: string, } | { "action": "expectations", expectations: Array<ValidationExpectation>, } | { "action": "create", title: string, objective: string, criteria: string, links: Array<WorkLink>, } | { "action": "update", title: string, objective: string, criteria: string, state: WorkState, } | { "action": "link", link: WorkLink, } | { "action": "unlink", kind: WorkLinkKind, reference: string, } | { "action": "note", text: string, };
export type WorkMutation = { id: string, eventId: string, actor: string,
/**
 * Zero for creation; otherwise the last revision read by the caller.
 */
expectedRevision: number, change: WorkChange, };
export type Request = { version: number, operation: Operation, repository: string | null, params: JsonValue, };
export type Response = { version: number, data: JsonValue, error: string | null, };
