use ts_rs::TS;
use worklens_core::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cfg = ts_rs::Config::default();
    let declarations = [
        serde_json::Value::decl(&cfg),
        Provenance::decl(&cfg),
        Availability::decl(&cfg),
        Repository::decl(&cfg),
        FileChange::decl(&cfg),
        Worktree::decl(&cfg),
        Branch::decl(&cfg),
        Remote::decl(&cfg),
        Commit::decl(&cfg),
        GitSnapshot::decl(&cfg),
        DiffResult::decl(&cfg),
        Document::decl(&cfg),
        ToolStatus::decl(&cfg),
        RelationKind::decl(&cfg),
        Evidence::decl(&cfg),
        Project::decl(&cfg),
        Edge::decl(&cfg),
        Graph::decl(&cfg),
        Impact::decl(&cfg),
        AgentState::decl(&cfg),
        AgentSession::decl(&cfg),
        Operation::decl(&cfg),
        WorkState::decl(&cfg),
        WorkLinkKind::decl(&cfg),
        WorkLinkStatus::decl(&cfg),
        WorkLink::decl(&cfg),
        WorkItem::decl(&cfg),
        WorkEvent::decl(&cfg),
        WorkDetail::decl(&cfg),
        WorkList::decl(&cfg),
        WorkResult::decl(&cfg),
        WorkChange::decl(&cfg),
        WorkMutation::decl(&cfg),
        Request::decl(&cfg),
        Response::decl(&cfg),
    ];
    let text = format!(
        "// Generated by cargo run -p worklens-core --bin export-contracts. Do not edit.\n{}\n",
        declarations
            .iter()
            .map(|d| format!("export {d}")
                .lines()
                .map(str::trim_end)
                .collect::<Vec<_>>()
                .join("\n"))
            .collect::<Vec<_>>()
            .join("\n")
    );
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../packages/contracts/src/index.ts");
    if std::env::args().any(|a| a == "--check") {
        if std::fs::read_to_string(path)? != text {
            return Err("Generated contracts are out of date".into());
        }
    } else {
        std::fs::create_dir_all(path.parent().ok_or("missing parent")?)?;
        std::fs::write(path, text)?;
    }
    Ok(())
}
